### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by j2l** [zlatnaspirala/compositor#2]
;)

**Comment by zlatnaspirala** [comment]
I will add MIT.
 Thanks for comment if you wanna collaborate you can join me on any repo you like.

**Comment by j2l** [comment]
Great! 
And thanks for the warm welcome in your project.
I'm using Svelte. Do you have plans to develop with it?

**Comment by zlatnaspirala** [comment]
> Great! And thanks for the warm welcome in your project. I'm using Svelte. Do you have plans to develop with it?

 It is popular I heard about Svetle but never try. Sounds good looks like Svetle relies on the (build in ) native html/css/js staff
 - I sow NO Virtual DOMS .
 It is hard for me to start new project because i already have 10 project in deep dev mode.
 
 You can watch this project i will add other input options. It will be strong module orientend because i wanna use this project in other my apps like RECORD GAMEPLAY for example.

Greetings!
